---
abstract: 'A cookie-based single sign-on system for Apache'
author:
  - 'Maciej Pasternacki <maciej@pasternacki.net>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-Authen-OdinAuth
provides:
  Apache2::Authen::OdinAuth:
    file: lib/Apache2/Authen/OdinAuth.pm
    version: 0.6
  Crypt::OdinAuth:
    file: lib/Crypt/OdinAuth.pm
    version: 0.2
requires:
  Digest::HMAC: 0
  Digest::SHA256: 0
  MIME::Base64: 3.13
  YAML::XS: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.6
